import * as ReSpec from "../src/respec.js";

const modules = [
  // order is significant
  import("../src/core/location-hash.js"),
  import("../src/core/l10n.js"),
  import("../src/pcisig/pcisig-defaults.js"),
  import("../src/core/style.js"),
  import("../src/pcisig/pcisig-style.js"),
  import("../src/core/github.js"),
  import("../src/core/data-include.js"),
  import("../src/core/markdown.js"),
  import("../src/pcisig/pcisig-headers.js"),
  import("../src/pcisig/footnotes.js"),
  import("../src/pcisig/pcisig-conformance.js"),
  import("../src/core/data-transform.js"),
  import("../src/core/inlines.js"),
  import("../src/core/examples.js"),
  import("../src/core/issues-notes.js"),
  import("../src/pcisig/impnote.js"),
  import("../src/core/requirements.js"),
  import("../src/core/best-practices.js"),
  import("../src/pcisig/regpict.js"),
  import("../src/core/figures.js"),
  import("../src/pcisig/tables.js"),
  import("../src/pcisig/equations.js"),
  import("../src/pcisig/pre-dfn.js"),
  import("../src/core/dfn.js"),
  import("../src/core/data-cite.js"),
  import("../src/pcisig/link-to-dfn.js"),
  import("../src/core/contrib.js"),
  import("../src/core/fix-headers.js"),
  import("../src/core/structure.js"),
  import("../src/core/informative.js"),
  import("../src/core/id-headers.js"),
  import("../src/pcisig/fig-tbl-eqn-numbering.js"),
  import("../src/pcisig/aria.js"),
  import("../src/pcisig/xref-map.js"),
  import("../src/ui/about-respec.js"),
  import("../src/ui/save-html.js"),
  import("../src/core/data-tests.js"),
  import("../src/pcisig/include-final-config.js"),
  import("../src/pcisig/empty-references.js"),
];

export default ReSpec.run(modules);
