This specification describes the conformance criteria for
<dfn data-lt="Hydra API documentation">Hydra API documentations</dfn>
and <dfn data-lt="Hydra client">Hydra clients</dfn>. These criteria are
relevant to authors, authoring tool implementers, and client
implementers. All authoring guidelines, diagrams, examples, and notes
in this specification are non-normative, as are all sections
explicitly marked as non-normative. Everything else in this
specification is normative.</p>

<p class="issue">
Conformance for Hydra clients should probably not be specified in this document.
</p>

<p class="issue">Add normative statements</p>

The key words MUST, MUST NOT, REQUIRED, SHALL, SHALL NOT, SHOULD,
SHOULD NOT, RECOMMENDED, NOT RECOMMENDED, MAY, and OPTIONAL in this
specification have the meaning defined in [[!RFC2119]].

