export const idlKeywords = new Set([
  "any",
  "attribute",
  "boolean",
  "byte",
  "ByteString",
  "callback",
  "const",
  "creator",
  "Date",
  "deleter",
  "dictionary",
  "DOMString",
  "double",
  "enum",
  "false",
  "float",
  "getter",
  "implements",
  "Infinity",
  "inherit",
  "interface",
  "iterable",
  "long",
  "maplike",
  "NaN",
  "null",
  "object",
  "octet",
  "optional",
  "or",
  "partial",
  "readonly",
  "RegExp",
  "required",
  "sequence",
  "setlike",
  "setter",
  "short",
  "static",
  "stringifier",
  "true",
  "typedef",
  "unrestricted",
  "unsigned",
  "USVString",
  "void",
]);
export const idlAttributeNameKeyword = new Set(["required"]);
export const idlArgumentNameKeyword = new Set([
  "attribute",
  "callback",
  "const",
  "creator",
  "deleter",
  "dictionary",
  "enum",
  "getter",
  "implements",
  "inherit",
  "interface",
  "iterable",
  "maplike",
  "partial",
  "required",
  "setlike",
  "setter",
  "static",
  "stringifier",
  "typedef",
  "unrestricted",
]);

export const idlType = {
  sequence: false,
  generic: null,
  nullable: false,
  union: false,
  idlType: "",
};

export const idlOperation = {
  type: "operation",
  getter: false,
  setter: false,
  creator: false,
  deleter: false,
  static: false,
  stringifier: false,
  idlType: { ...idlType },
  name: "",
  arguments: [],
  extAttrs: [],
};
// https://heycam.github.io/webidl/#Exposed
export const idlExposedKeywords = new Set([
  "PrimaryGlobal",
  "Global",
  "Exposed",
]);

// These are listed as undesirable things in the Web IDL spec.
export const idlUndesirableExtAttrs = new Set([
  "LegacyArrayClass",
  "LegacyNamespace",
  "LegacyUnenumerableNamedProperties",
  "LegacyWindowAlias",
  "NamedConstructor",
  "NoInterfaceObject",
  "OverrideBuiltins",
  "TreatNonObjectAsNull",
  "TreatNullAs",
]);