name: Regressions
on: workflow_dispatch

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
  FORCE_COLOR: 1

jobs:
  build:
    name: Build respec-w3c
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-12-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run build:w3c
      - uses: actions/upload-artifact@v2
        with:
          name: builds
          path: |
            builds/respec-w3c.js*
            builds/respec-worker.js*
            builds/respec-highlight.js*
          retention-days: 3

  test:
    name: Diff ${{ matrix.source }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        source:
          - https://w3c.github.io/manifest/
          - https://w3c.github.io/payment-request/
          - https://w3c.github.io/trace-context/
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-12-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci --production --ignore-scripts
      - uses: actions/download-artifact@v2
        with:
          name: builds
          path: ./builds/
      - run: git status
      - run: node ./tools/respec2html ${{ matrix.source }} live.html -t 30 --verbose
      - run: node ./tools/respec2html ${{ matrix.source }} now.html -t 30 --verbose --use-local
      - run: git diff --no-index live.html now.html --exit-code
